import { BLOG_NAME } from 'lib/constants'
import Head from 'next/head'
import Layout from 'src/layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>{BLOG_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </Layout>
  )
}
